MonCatalogueProduitCategorie/Controllers/CategorieController.cs
using Microsoft.AspNetCore.Mvc;

namespace MonCatalogueProduitCategorie.Controllers
{
    public class CategorieController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

MonCatalogueProduitCategorie/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using MonCatalogueProduitCategorie.Models;
using MonCatalogueProduitCategorie.Service;
using System.Diagnostics;

namespace MonCatalogueProduitCategorie.Controllers
{
    public class HomeController : Controller
    {
 
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MonCatalogueProduitCategorie/Controllers/ProduitController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MonCatalogueProduitCategorie.Service;

namespace MonCatalogueProduitCategorie.Controllers
{
    public class ProduitController : Controller
    {
        //property
        public CatalogueDBContext dbContext { get; set; }
        public ProduitController(CatalogueDBContext db)
        {
            dbContext= db; 
        }
       
        //GET: /Produit/Index
        public IActionResult Index(int numeroPage=0, int size=3, string motCle="")
        {
            int position = numeroPage * size;

            IEnumerable<Produit> allProducts = dbContext.Produits.Skip(position).Take(size).Include(p=>p.Categorie).ToList();
            ViewBag.currentPage = numeroPage;
            /*if pair this below instruction is valid and else how to make ?? */
            //-- int totalPages = dbContext.Produits.ToList().Count / size; --
            /* si totalPages est impaire(est un nombre a virgule) Comment Faire ?? */
            int  totalPages;
            int nombreProduits= dbContext.Produits.ToList().Count;
            if (nombreProduits % size == 0)
               ViewBag.totalPages = nombreProduits / size;
            else
                ViewBag.totalPages = 1+(nombreProduits / size);
            return View("Produits", allProducts);
        }

        public IActionResult Create()
        {
            //loading of category or foreign key management
            IEnumerable<Categorie>allCategories = dbContext.Categories.ToList();
            Produit p = new();
            
            ViewBag.categories = allCategories;

            return View("Create",p);
        }

        [HttpPost]
        public IActionResult Save( Produit p)
        {
            if (ModelState.IsValid)
            {
                dbContext.Produits.Add(p);
                dbContext.SaveChanges();

                return RedirectToAction("Index");
            }
            return View("Produits",p);

        }
    }
}
 

MonCatalogueProduitCategorie/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

MonCatalogueProduitCategorie/Views/Produit/Create.cshtml
@using MonCatalogueProduitCategorie.Service
@model Produit
 <!--<span asp-validation-for="J1Chambres" class="text-danger"></span>--> 
<div class="container">
   <div class="panel panel-primary">
            <div class="panel-heading">
               Ajouter un nouveau produit
            </div>

       <div class="panel-body">
          <div class="col-md-12">
             <form method="post" asp-action="Save">
                     <div class="container">
                        <div class="form-group">
                            <div class=" row">
                                <div class="col-6">

                                        <label for="des" class="control-label">Désignation</label>
                                        <input name="Designation" type="text" value="@Model.Designation" class="form-control" />
                                     @Html.ValidationMessageFor(p=>p.Designation, "", new{ @class="text-danger"})
                              </div>    
                            </div>
                       </div>
                    </div>

                 <div class="container">
                        <div class="form-group">
                            <div class=" row">
                                <div class="col-6">
                                        <label for="prix" class="control-label">Prix</label>
                                        <input class="form-control" name="Prix" type="number" value="@Model.Prix" />
                                        @Html.ValidationMessageFor(p=>p.Prix, "", new{ @class="text-danger"})
                                 </div>    
                            </div>
                       </div>
                    </div>

                     <div class="container">
                        <div class="form-group">
                            <div class=" row">
                                <div class="col-6">
                                        <label for="quantite" class="control-label">Quantite</label>
                                        <input class="form-control" name="Quantite" type="number" value="@Model.Quantite" />
                                        @Html.ValidationMessageFor(p=>p.Quantite, "", new{ @class="text-danger"}) 
                                </div>    
                            </div>
                       </div>
                    </div>

                  <div class="container">
                        <div class="form-group">
                            <div class=" row">
                                <div class="col-6">

                    <label for="categorie" class="control-label">Categorie:</label>

                     <select name="CategorieID">

                        @{
                        foreach( MonCatalogueProduitCategorie.Service.Categorie item in ViewBag.categories)
                         {
                            <option value="@item.CategorieID" >@item.CategorieName</option>
                         }


                        }

                    </select>

                                </div>    
                            </div>
                       </div>
                    </div>
                   <div class="d-grid gap-2 d-md-block">
                        <button class="btn btn-primary" type="submit">Envoyer</button>
                    </div>
              </form>
           </div>
       </div>
   </div>
</div>

MonCatalogueProduitCategorie/Views/Produit/Produits.cshtml
@using MonCatalogueProduitCategorie.Service
@model IEnumerable<Produit>


  <div class="d-flex">
         <div class="mr-auto p-2">
             <a class="btn btn-primary" asp-action="Create">Nouveau Produit</a>
         </div>
  </div>
     

  <div class="panel panel-primary">
          <div class="panel-heading">Liste des produits</div>

          <div class="container mb-1">
              <form method="get" asp-action='Index'>
                  <label for="a">mot clé</label>
                  <input id="a" type="text" name="motCle"/>
                  <button class="btn btn-primary" type="submit">chercher</button>
              </form>
          </div>
         <div class="panel-body">

         <table class="table table-striped">
                    <tr>
                        <th>ID</th>

                         <th>
                              Designation
                         </th>

                        <th>Prix</th>

                        <th>Quantité</th>

                        <th>Categorie</th>
                    </tr>
                             @foreach(var item in Model)
                           {
                               <tr>
                                   <td>
                                       @item.ProduitID
                                   </td>
                                   <td>
                                       @item.Designation
                                   </td>
                                                      <td>
                                       @item.Prix
                                   </td>
                                   <td>
                                       @item.Quantite
                                   </td>
                                   <td>
                                       @item.Categorie.CategorieName
                                   </td>
                               </tr>
                           }
         </table>
 
         </div>
         <div>
             <ul class="nav nav-pills">
                @{
                    for(int i=0; i<ViewBag.totalPages;i++)
                    {
                        string className = "";
                        if(i==ViewBag.currentPage)
                        {
                            className = "active";
                        }
                        <li class="@className">
                             <a asp-action="Index" asp-route-numeroPage="@i">@i</a>
                         </li>
                    }
                 }    
             </ul>
         </div>
  </div>

MonCatalogueProduitCategorie/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MonCatalogueProduitCategorie</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MonCatalogueProduitCategorie.styles.css" asp-append-version="true" />
<!-------------------------------Boostrap CSS------------------------------------------->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">


</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MonCatalogueProduitCategorie</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Produit" asp-action="Index">Produits</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">About</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Contact</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - MonCatalogueProduitCategorie - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <!------------------------------------Boostrap js-------------------------------------------->
    <!-- Latest compiled and minified JavaScript -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>  
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>